### PR TITLE
Enabling 'single-host' route exposure strategy by default

### PR DESCRIPTION
**Pull request by ibuziuk**
Known issues:
 - welcome page - https://github.com/eclipse/che/issues/17694

### CODE REVIEW

**Comment by ibuziuk** [comment]
@pdaverh as we discussed on the prio call - `single-host` is expected to be enabled by default

**Comment by MatousJobanek** [comment]
@ibuziuk is this going to work (and should be applied) also in CRT cluster? ~if not then let's create a separate file for OSD Sandbox stuff.~ if yes, then please update also the `che_cluster.yaml` file

**Comment by alexeykazakov** [comment]
Yeah.. we need to keep both che and crw configuration in sync (see https://github.com/codeready-toolchain/toolchain-infra/blob/master/config/operators/che/che_cluster.yaml). So, no matter what operator we use (che or crw) in different environments we use the same configuration. Unless there is a good reason to have different configurations.

**Comment by ibuziuk** [comment]
@alexeykazakov @MatousJobanek why can't we simply drop `che_cluster.yaml`? I thought that the business decision is to run against the product (not the project)?

**Comment by alexeykazakov** [comment]
We haven't switched crt-stage to CRW yet. It's still running Che.

**Comment by ibuziuk** [comment]
ok, updated che also, but I believe we should consider dropping the project setup and focus only on the product in the short run

**Review by alexeykazakov — APPROVED** [review]

**Comment by alexeykazakov** [comment]
Hm.. This doesn't work in Che 7.19.2. It breaks dashboard login.

**Comment by ibuziuk** [comment]
There is a known issue for switching between multihost & single host - https://github.com/eclipse/che/issues/17886
However, since we are currently planning to use single-host from the very beginning we will not be affected.
Workaround for switching between multihost & singlehost -  https://github.com/eclipse/che/issues/17886#issuecomment-693504404

**Review by alexeykazakov — APPROVED** [review]

**Pull request merged**
